SELECT 
    SALESPERSON,
    CUSTOMERNAME,
    CARMAKE,
    CARMODEL,
    SALEPRICE,
    COMMISSIONRATE AS COMRATE,
    COMMISSIONEARNED AS COMEARNED,
    try_cast(CARYEAR AS NUMBER) AS CARYEAR,
    try_cast(DDATE AS DATE) AS DDATE
FROM {{ source ("raw_bi_car","CAR_SALES") }}
WHERE try_cast(DDATE AS DATE) > '2020-01-01'